### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by EnterJokeHere1** [GuglioIsStupid/Vs-Kero-3DS#1]
Everytime i launch the game i get a pop up that says (in spanish) "To use this program, its necesarry to update it to its latest version."
Why?
![image](https://github.com/GuglioIsStupid/Vs-Kero-3DS/assets/75617531/bcbd2d56-787e-4d05-8b2c-67d5df5b4054)

**Comment by GuglioIsStupid** [comment]
I have no idea, until I figure it out, I have removed the CIA version from the releases until I figure it out (I have never done CIA file compiling before).

Please use the 3dsx version

**Comment by GuglioIsStupid** [comment]
Use the 3dsx of this version https://github.com/GuglioIsStupid/Vs-Kero-3DS/releases/tag/v0.3.0

**Comment by EnterJokeHere1** [comment]
thanks
