### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by Lumaah** [GuglioIsStupid/Vs-Kero-3DS#2]
Hello , i would like to know how i could build this myself so i can try using custom assets

**Comment by GuglioIsStupid** [comment]
To build, simply install "lovebrew" and run "lovebrew build" in the root folder
https://github.com/lovebrew/lovebrew/releases
If the latest doesn't work, use 0.6.0

**Comment by Lumaah** [comment]
Thanks dude !
